### Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

```python
pd.__version__
```

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.1'

### Getting the data 

For this homework, we'll use the Laptops Price dataset. Download it from 
[here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv).

You can do it with wget:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
```

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [3]:
df_laptops = pd.read_csv('laptops.csv')

### Q2. Records count

How many records are in the dataset?

- 12
- 1000
- 2160 <-
- 12160

In [4]:
df_laptops.shape

(2160, 12)

In [5]:
df_laptops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


### Q3. Laptop brands

How many laptop brands are presented in the dataset?

- 12
- 27 <-
- 28
- 2160

In [6]:
df_laptops.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [8]:
len(df_laptops.Brand.unique())

27

### Q4. Missing values

How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3 <-

In [34]:
len(df_laptops.columns[df_laptops.isnull().any()])

3

### Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

- 869
- 3691
- 3849
- 3936 <-

In [13]:
dell_laptops = df_laptops[df_laptops.Brand == 'Dell']
dell_laptops.head()

Laptop Status Brand     Model  \
161  Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...    New  Dell    Vostro   
271  Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...    New  Dell    Vostro   
281  Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...    New  Dell    Vostro   
319  Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...    New  Dell  Latitude   
328  Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...    New  Dell    Vostro   

               CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
161  Intel Core i3    8      256          SSD  NaN    15.6    No       599.00  
271  Intel Core i5    8      256          SSD  NaN    15.6    No       690.15  
281  Intel Core i7   16      512          SSD  NaN    15.6    No       889.00  
319  Intel Core i5    8      256          SSD  NaN    15.6    No       789.00  
328  Intel Core i5   16      512          SSD  NaN    15.6    No       869.00

In [16]:
dell_laptops.sort_values(by='Final Price', ascending=False)

Laptop       Status Brand  \
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...          New  Dell   
1334  Dell Precision 5470 Intel Core i7-12800H/16GB/...          New  Dell   
1346  Dell XPS 15 9520 Intel Core i7-12700H/16GB RAM...          New  Dell   
1347  Dell XPS 15 9520 Intel Core i7-12700H/32GB/1TB...  Refurbished  Dell   
1323  Dell Latitude 5520 Intel Core i5-1135G7/8GB/25...          New  Dell   
...                                                 ...          ...   ...   
1839  Dell Latitude E5550 Intel Core i5-5300U/8GB/12...  Refurbished  Dell   
1836  Dell Latitude 5480 Intel Core i5-7300U/8GB/256...  Refurbished  Dell   
809   Dell Latitude E7450 Intel Core i5-5300U/8GB/25...  Refurbished  Dell   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
633   Dell Latitude E5440 Intel Core i5-4310U/8GB/12...  Refurbished  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   
1334  Precision  Intel Core i7   16      512          SSD  RTX A1000    14.0   
1346        XPS  Intel Core i7   16     1000          SSD   RTX 3050    15.6   
1347        XPS  Intel Core i7   32     1000          SSD   RTX 3050    15.6   
1323   Latitude  Intel Core i5    8      256          SSD        NaN    15.6   
...         ...            ...  ...      ...          ...        ...     ...   
1839   Latitude  Intel Core i5    8      128          SSD        NaN    15.6   
1836   Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
809    Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1843     Vostro  Intel Core i5    8      256          SSD        NaN    13.3   
633    Latitude  Intel Core i5    8      128          SSD        NaN    14.0   

     Touch  Final Price  
1335   Yes      3936.00  
1334    No      3469.00  
1346    No      3012.09  
1347   Yes      2818.09  
1323    No      2450.71  
...    ...          ...  
1839    No       489.00  
1836    No       489.00  
809     No       448.99  
1843    No       420.74  
633     No       379.00  

[84 rows x 12 columns]

In [17]:
dell_laptops['Final Price'].max()

3936.0

### Q6. Median value of Screen

1. Find the median value of `Screen` column in the dataset.
2. Next, calculate the most frequent value of the same `Screen` column.
3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.
4. Now, calculate the median value of `Screen` once again.

Has it changed?

> Hint: refer to existing `mode` and `median` functions to complete the task.

- Yes
- No <-

In [18]:
median = df_laptops.Screen.median()
median

15.6

In [19]:
mode = df_laptops.Screen.mode()
mode

0    15.6
Name: Screen, dtype: float64

In [20]:
df_laptops2 = df_laptops.copy()

In [21]:
df_laptops2.Screen = df_laptops.Screen.fillna(mode)

In [22]:
df_laptops2.Screen.median()

15.6

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.43
- 45.29
- 45.58
- 91.30 <-

In [23]:
import numpy as np

In [24]:
innjoo_laptops = df_laptops[df_laptops.Brand == 'Innjoo'][['RAM', 'Storage', 'Screen']]
innjoo_laptops

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [27]:
X = innjoo_laptops.values

In [28]:
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [29]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [30]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [31]:
w = (XTX_inv.dot(X.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [33]:
w.sum().round(2)

91.3